#!/usr/bin/bash

rm -f ~/Documents/gmon/gputempsold.log
mv ~/Documents/gmon/gputemps.log ~/Documents/gmon/gputempsold.log

filepath=~/Documents/gmon/gputemps.log

while true
do
    clear
    #options for grep are as follows:
    # o: only matching. it will only bother with the text that directly matches the regex expression.
    # w: only selects lines containing matches that form whole words.
    # E: interpret patterns as extended regular expressions
    # e: use patterns as the patterns.
    nvidia-smi | grep -owEe '[0-9]+C' | tee -a $filepath
    nvidia-smi | grep -owEe '\|\s[0-9]+%' | tee -a $filepath
    nvidia-smi | grep -oEe '\s[0-9][0-9]:+[0-9]+:+[0-9]+' | tee -a $filepath
    sed -i 's/|\s//g' $filepath

    sleep 2
done
