#!/usr/bin/bash

###############################################################################
# Copyright (c) ValenceElectron (Github: ValenceElectron,                     #
# Twitter: TheLastElectron, Email: TheLastElectronSPDF@gmail.com)             #
#-----------------------------------------------------------------------------#
# Program that monitors various aspects of your GPU and displays them in a    #
# window. Also allows for settings custom fan curves.                         #
#-----------------------------------------------------------------------------#
# This file is part of the gmon_parser project.                               #
###############################################################################
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

nvidia-settings -a [gpu:0]/GPUFanControlState=$1 -a [fan:0]/GPUTargetFanSpeed=$2