#!/usr/bin/bash

###############################################################################
# Copyright (c) ValenceElectron (Github: ValenceElectron,                     #
# Twitter: TheLastElectron, Email: TheLastElectronSPDF@gmail.com)             #
#-----------------------------------------------------------------------------#
# Program that monitors various aspects of your GPU and displays them in a    #
# window. Also allows for settings custom fan curves.                         #
#-----------------------------------------------------------------------------#
# This file is part of the gmon_parser project.                               #
###############################################################################
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

filepath=~/.local/bin/gmon_parser/logs/gputemps.log

mkdir -p ~/.local/bin/gmon_parser/logs
rm -f $filepath
nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader | tee -a $filepath