#!/usr/bin/bash

filepath=~/.local/bin/gmon_parser/logs/gputemps.log

mkdir -p ~/.local/bin/gmon_parser/logs
rm -f $filepath
nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader | tee -a $filepath