// Made by ValenceElectron (Github: ValenceElectron, Twitter: TheLastElectron, Email: TheLastElectronSPDF@gmail.com)

/*
**************************************************
 * Simple program that takes the gputemps.txt    *
 * file generated by my gmon bash script and     *
 * outputs the relevant GPU temp information     *
 * in a neat and concise format. gmon simply     *
 * runs "nvidia-smi" every two seconds to gather *
 * information and store it in the above .txt    *
 *************************************************
 * */

import java.io.IOException;

public class Boot {

    public static void main(String[] args) throws IOException { new Main("gmon"); }
}