// Made by Valence Electron @ Valence-Shell

import java.io.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.StringTokenizer;

/*************************************************
 * Simple program that takes the gputemps.txt    *
 * file generated by my gmon bash script and     *
 * outputs the relevant GPU temp information     *
 * in a neat and concise format. gmon simply     *
 * runs "nvidia-smi" every ten seconds to gather *
 * information and store it in the above .txt    *
 ************************************************/

public class Main {
    static private TempExtract tpEx;
    static private TempStats tpSt;
    static private int[] temps;

    public static void main(String[] args) throws IOException {
        tpEx = new TempExtract();
        tpEx.ExtractTemps();
        temps = tpEx.GetTemps();

        Arrays.sort(temps);

        tpSt = new TempStats(temps);
    }
}