// Made by Valence Electron @ Valence-Shell

import java.io.*;
import java.util.Arrays;

/*************************************************
 * Simple program that takes the gputemps.txt    *
 * file generated by my gmon bash script and     *
 * outputs the relevant GPU temp information     *
 * in a neat and concise format. gmon simply     *
 * runs "nvidia-smi" every two seconds to gather *
 * information and store it in the above .txt    *
 ************************************************/

public class Main {

    public static void main(String[] args) throws IOException {
        TempExtract tpEx = new TempExtract();
        tpEx.ExtractTemps();

        int[] temps = tpEx.GetTemps();
        Arrays.sort(temps);
        FormatAndDisplay displayTemps = new FormatAndDisplay(temps, "Temps");
    }
}